ALTER TABLE review_scores_dim
DROP CONSTRAINT IF EXISTS fk_review_listing CASCADE,
DROP CONSTRAINT IF EXISTS review_scores_dim_pkey CASCADE;

ALTER TABLE review_scores_dim
ADD COLUMN review_scores_dim_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
ADD COLUMN IF NOT EXISTS valid_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
ADD COLUMN IF NOT EXISTS valid_to TIMESTAMP, 
ADD COLUMN IF NOT EXISTS is_current BOOLEAN DEFAULT TRUE;